# File name: kivygui.py

<Button>:
    font_size: 40
    color: 0,1,0,1
    size_hint: 0.3,0.2

<FloatLayout>:
    Button:
        text:"Kivy"
        pos_hint: {"x":0,"y":0.5}

    Button:
        text:"Tutorials"
        pos_hint:{"right":1,"top":1}

# <Widgets>:
#     Button:
#         pos: root.x, root.top - self.height
#         text: "Kivy"
#
#     Button:
#         pos: 175,0
#         text: "Tutorials"
